In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import make_multilabel_classification
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import CCA

import sklearn
from sklearn.model_selection import train_test_split

In [3]:
>>> from sklearn.datasets import make_classification
>>> from sklearn.multioutput import MultiOutputClassifier
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.utils import shuffle
>>> import numpy as np

In [4]:
import pandas as pd

In [5]:
X_train = pd.read_csv("Rec_sys_set/X_train", sep="\t")
y_train = pd.read_csv("Rec_sys_set/y_train", sep="\t")

In [6]:
fitted = multi_target_forest.fit(X_train, y_train)
#.score(X_train, y_train)

In [7]:
from joblib import dump, load
dump(fitted, "multi_target_forest.joblib")

['multi_target_forest.joblib']

In [8]:
fitted.score(X_train, y_train)

5.009052899837052e-06

In [34]:
fitted

MultiOutputClassifier(estimator=RandomForestClassifier(bootstrap=True,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       n_estimators=100,
                                                       n_jobs=None,
                                                       oob_score=False,
                                                       random_state=1,
                                                       verbose=0,
                                                       warm_start=False),
                      n_jobs=-1)

In [9]:
X_train

,Category_ref_0.0,Category_ref_1.0,Category_ref_2.0,Category_ref_3.0,Category_ref_4.0,Category_ref_5.0,Category_ref_6.0,Category_ref_7.0,Category_ref_8.0,Category_ref_9.0,...,attr_ref_84,attr_ref_85,attr_ref_86,attr_ref_87,attr_ref_88,attr_ref_89,attr_ref_9,attr_ref_90,attr_ref_91,attr_ref_nan
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595296,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2595297,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2595298,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2595299,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2595300,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

---

In [6]:
OHE_w_attrs_only = pd.read_csv("Rec_sys_set/OHE_all_pairs_atleast_one_attr", sep="\t")

In [7]:
OHE_w_attrs_only = OHE_w_attrs_only.drop(columns = ["ClassId_ref", "ClassId_paired"])

OHE_w_attrs_only.loc[(OHE_w_attrs_only == 2).any(axis=1),:]

Empty DataFrame
Columns: [ImageId, attr_0_ref, attr_1_ref, attr_10_ref, attr_11_ref, attr_12_ref, attr_13_ref, attr_14_ref, attr_15_ref, attr_16_ref, attr_17_ref, attr_18_ref, attr_19_ref, attr_2_ref, attr_20_ref, attr_21_ref, attr_22_ref, attr_23_ref, attr_24_ref, attr_25_ref, attr_26_ref, attr_27_ref, attr_28_ref, attr_29_ref, attr_3_ref, attr_30_ref, attr_31_ref, attr_32_ref, attr_33_ref, attr_34_ref, attr_35_ref, attr_36_ref, attr_37_ref, attr_38_ref, attr_39_ref, attr_4_ref, attr_40_ref, attr_41_ref, attr_42_ref, attr_43_ref, attr_44_ref, attr_45_ref, attr_46_ref, attr_47_ref, attr_48_ref, attr_49_ref, attr_5_ref, attr_50_ref, attr_51_ref, attr_52_ref, attr_53_ref, attr_54_ref, attr_55_ref, attr_56_ref, attr_57_ref, attr_58_ref, attr_59_ref, attr_6_ref, attr_60_ref, attr_61_ref, attr_62_ref, attr_63_ref, attr_64_ref, attr_65_ref, attr_66_ref, attr_67_ref, attr_68_ref, attr_69_ref, attr_7_ref, attr_70_ref, attr_71_ref, attr_72_ref, attr_73_ref, attr_74_ref, attr_75_ref, attr_76_ref, attr_77_ref, attr_78_ref, attr_79_ref, attr_8_ref, attr_80_ref, attr_81_ref, attr_82_ref, attr_83_ref, attr_84_ref, attr_85_ref, attr_86_ref, attr_87_ref, attr_88_ref, attr_89_ref, attr_9_ref, attr_90_ref, attr_91_ref, attr_0_paired, attr_1_paired, attr_10_paired, attr_11_paired, attr_12_paired, attr_13_paired, attr_14_paired, ...]
Index: []

[0 rows x 217 columns]

In [8]:
OHE_w_attrs_only

,ImageId,attr_0_ref,attr_1_ref,attr_10_ref,attr_11_ref,attr_12_ref,attr_13_ref,attr_14_ref,attr_15_ref,attr_16_ref,...,Category_paired_6,Category_paired_7,Category_paired_8,Category_paired_9,Category_paired_10,Category_paired_11,Category_paired_12,Category_paired_27,Category_paired_28,Category_paired_33
0,000aac3870ea7c59ca0333ffa5327323.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,000aac3870ea7c59ca0333ffa5327323.jpg,0,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,000e973c99dc090afd7898c93daf0dbc.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,000e973c99dc090afd7898c93daf0dbc.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,000e973c99dc090afd7898c93daf0dbc.jpg,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947,fff65379ba62e3f6498a20e9cc2a99fe.jpg,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
11948,fff65379ba62e3f6498a20e9cc2a99fe.jpg,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11949,fff65379ba62e3f6498a20e9cc2a99fe.jpg,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
11950,fff65379ba62e3f6498a20e9cc2a99fe.jpg,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11951,fff65379ba62e3f6498a20e9cc2a99fe.jpg,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [9]:
index_col, ref_cols, paired_cols = [["ImageId"], 
                                    [ref_col for ref_col in OHE_w_attrs_only.columns if "ref" in ref_col], 
                                    [paired_col for paired_col in OHE_w_attrs_only.columns if "paired" in paired_col]]

In [10]:
X = OHE_w_attrs_only.drop(columns = paired_cols + index_col)
y = OHE_w_attrs_only.drop(columns = ref_cols + index_col)

In [11]:
X.shape

(11952, 108)

In [12]:
y.shape

(11952, 108)

In [274]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [335]:
y_test.shape

(3586, 108)

In [336]:
X_test.shape

(3586, 108)

In [276]:
multi_target_forest_no_nan = MultiOutputClassifier(forest, n_jobs=-1)

In [277]:
fitted_no_nan = multi_target_forest_no_nan.fit(X_train, y_train)

In [278]:
fitted_no_nan.score(X_train, y_train)

0.27265120726751135

In [279]:
fitted_no_nan.score(X_test, y_test)

0.0039040713887339654

In [76]:
test_predict = fitted_no_nan.predict(X_test)

In [280]:
cat_cols = [col for col in y_test.columns if "Category" in col]
attribute_cols = [col for col in y_test.columns if "attr" in col]

In [281]:
test_predict_df = pd.DataFrame(test_predict,columns = y_test.columns)
test_predict_df.loc[:,cat_cols].idxmax(axis=1).value_counts()

Category_paired_0     2016
Category_paired_1      711
Category_paired_6      358
Category_paired_4      128
Category_paired_8      124
Category_paired_9       52
Category_paired_10      40
Category_paired_7       33
Category_paired_3       12
Category_paired_2       11
Category_paired_5        7
Category_paired_11       6
Category_paired_12       2
dtype: int64

In [282]:
y_test.loc[:,cat_cols].idxmax(axis=1).value_counts()

Category_paired_1     974
Category_paired_6     753
Category_paired_4     503
Category_paired_8     373
Category_paired_0     246
Category_paired_9     220
Category_paired_7     186
Category_paired_10    154
Category_paired_3      64
Category_paired_2      47
Category_paired_5      47
Category_paired_11     17
Category_paired_28      1
Category_paired_12      1
dtype: int64

In [283]:
test_predict_df.loc[:,attribute_cols].idxmax(axis=1).value_counts()

attr_20_paired    1966
attr_0_paired      823
attr_15_paired     388
attr_10_paired     112
attr_1_paired       90
attr_14_paired      64
attr_2_paired       14
attr_61_paired      14
attr_19_paired       7
attr_41_paired       5
attr_13_paired       4
attr_18_paired       4
attr_40_paired       2
attr_60_paired       2
attr_16_paired       1
attr_5_paired        1
attr_3_paired        1
attr_11_paired       1
attr_52_paired       1
dtype: int64

In [284]:
y_test.loc[:,attribute_cols].idxmax(axis=1).value_counts()

attr_0_paired     1135
attr_15_paired     701
attr_20_paired     699
attr_1_paired      337
attr_10_paired     255
attr_14_paired     228
attr_2_paired       56
attr_18_paired      39
attr_61_paired      34
attr_19_paired      30
attr_60_paired      20
attr_11_paired      15
attr_13_paired       9
attr_41_paired       6
attr_3_paired        6
attr_42_paired       4
attr_12_paired       4
attr_16_paired       4
attr_49_paired       1
attr_25_paired       1
attr_40_paired       1
attr_17_paired       1
dtype: int64

In [285]:
test_predict_df.loc[:,attribute_cols].sum(axis=1).value_counts()

4     976
5     766
3     739
6     479
2     266
7     209
8      35
1      19
9       7
14      3
13      1
dtype: int64

In [286]:
y_test.loc[:,attribute_cols].sum(axis=1).value_counts()

6     1374
7     1094
5      527
8      239
4      144
3       80
2       72
1       33
9       21
10       2
dtype: int64

In [287]:
y_test.loc[:,attribute_cols]

,attr_0_paired,attr_1_paired,attr_10_paired,attr_11_paired,attr_12_paired,attr_13_paired,attr_14_paired,attr_15_paired,attr_16_paired,attr_17_paired,...,attr_83_paired,attr_84_paired,attr_85_paired,attr_86_paired,attr_87_paired,attr_88_paired,attr_89_paired,attr_9_paired,attr_90_paired,attr_91_paired
10108,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8888,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3952,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
360,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3781,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5638,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6975,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3333,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9478,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3914,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

---

In [92]:
# import scipy

In [86]:
# from skmultilearn.problem_transform import BinaryRelevance
# from sklearn.svm import SVC

In [87]:
# clf = BinaryRelevance(
#     classifier=SVC(),
#     require_dense=[False, True]
# )

In [89]:
# from skmultilearn.dataset import load_dataset
# X_train, y_train, feature_names, label_names = load_dataset('emotions', 'train')
# X_test, y_test, _, _ = load_dataset('emotions', 'test')

emotions:train - exists, not redownloading
emotions:test - exists, not redownloading

In [90]:
# y_train.todense()

matrix([[0, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1],
        ...,
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0],
        [0, 1, 1, 0, 0, 0]])

In [102]:
# X_train_sparse = scipy.sparse.lil.lil_matrix(X_train)
# y_train_sparse = scipy.sparse.lil.lil_matrix(y_train)

In [288]:
# clf.fit(X_train_sparse, y_train_sparse)

In [289]:
# import seaborn as sns; sns.set()

In [13]:
OHE_w_attrs_only = pd.read_csv("Rec_sys_set/OHE_all_pairs_atleast_one_attr", sep="\t")
OHE_w_attrs_only = OHE_w_attrs_only.drop(columns = ["ClassId_ref", "ClassId_paired"])

In [14]:
OHE_w_attrs_only.loc[:,ref_cols + paired_cols].columns

Index(['attr_0_ref', 'attr_1_ref', 'attr_10_ref', 'attr_11_ref', 'attr_12_ref',
       'attr_13_ref', 'attr_14_ref', 'attr_15_ref', 'attr_16_ref',
       'attr_17_ref',
       ...
       'Category_paired_6', 'Category_paired_7', 'Category_paired_8',
       'Category_paired_9', 'Category_paired_10', 'Category_paired_11',
       'Category_paired_12', 'Category_paired_27', 'Category_paired_28',
       'Category_paired_33'],
      dtype='object', length=216)

In [15]:
col_names_transformed = [(f"Col_name:{col}",
  "Item: Reference" if "ref" in col else "Item: Paired",
  "Type : Attribute" if "attr" in col else "Type: Category") for col in ref_cols + paired_cols]

In [16]:
OHE_w_attrs_only = OHE_w_attrs_only.loc[:,ref_cols + paired_cols]
OHE_w_attrs_only.columns = col_names_transformed

co_occur_mat = OHE_w_attrs_only.T.dot(OHE_w_attrs_only)

co_occur_mat.to_csv("co_occur_matrix.tsv", sep="\t")

In [115]:
from Ipython.display import IFrame

In [325]:
IFrame("https://amp.pharm.mssm.edu/clustergrammer/viz_sim_mats/5dca2a1fd367f14819d47d64/co_occur_matrix.tsv", width = 800, height=1000)

In [291]:
train_predict = fitted_no_nan.predict(X_train)

In [292]:
a = (1- (np.count_nonzero(y_train != train_predict, axis=1)/y_train.count(axis=1))).mean()
a

0.967280482729921

In [293]:
b = (1- (np.count_nonzero(np.zeros_like(y_train) != y_train, axis=1)/y_train.count(axis=1))).mean()
b

0.9349450155390868

In [294]:
a/b

1.034585421231632

In [295]:
train_predict[4366]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [296]:
np.nonzero(train_predict[4366])

(array([ 7, 13, 58]),)

In [297]:
np.nonzero(y_train.loc[4366,:])

/Users/anhoang/anaconda3/envs/cv-hw/lib/python3.7/site-packages/numpy/core/fromnumeric.py:61: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return bound(*args, **kwds)

(array([ 0, 13, 36, 57, 58, 91, 93]),)

In [298]:
np.count_nonzero(y_train.loc[4366,:] != train_predict[4366])

6

In [299]:
train_predict.shape

(8366, 108)

In [300]:
y_train.shape

(8366, 108)

In [301]:
set(np.nonzero(train_predict[4366])[0])

{7, 13, 58}

In [302]:
set(np.nonzero(y_train.loc[4366,:])[0])

{0, 13, 36, 57, 58, 91, 93}

In [303]:
set(np.nonzero(y_train.loc[4366,:])[0]) - set(np.nonzero(train_predict[4366])[0])

{0, 36, 57, 91, 93}

In [304]:
np.size(np.setdiff1d(np.nonzero(train_predict[4366])[0], np.nonzero(y_train.loc[4366,:])[0]))

1

In [305]:
np.setdiff1d(np.nonzero(train_predict)[1],np.nonzero(y_train.values)[1])

array([], dtype=int64)

In [306]:
import skmultilearn

In [341]:
X_train

,attr_0_ref,attr_1_ref,attr_10_ref,attr_11_ref,attr_12_ref,attr_13_ref,attr_14_ref,attr_15_ref,attr_16_ref,attr_17_ref,...,Category_ref_6,Category_ref_7,Category_ref_8,Category_ref_9,Category_ref_10,Category_ref_11,Category_ref_12,Category_ref_27,Category_ref_28,Category_ref_33
4353,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3053,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8859,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
976,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8379,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5191,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
5390,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
860,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7270,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [340]:
y_train

,attr_0_paired,attr_1_paired,attr_10_paired,attr_11_paired,attr_12_paired,attr_13_paired,attr_14_paired,attr_15_paired,attr_16_paired,attr_17_paired,...,Category_paired_6,Category_paired_7,Category_paired_8,Category_paired_9,Category_paired_10,Category_paired_11,Category_paired_12,Category_paired_27,Category_paired_28,Category_paired_33
4353,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3053,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
8859,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
976,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8379,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5191,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5390,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
860,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
7270,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [308]:
import sklearn.metrics as metrics

metrics.hamming_loss(y_train, train_predict)

0.03271951727007907

In [326]:
metrics.hamming_loss(y_test, fitted_no_nan.predict(X_test))

0.05468540207804012

In [332]:
metrics.hamming_loss(y_test, np.zeros_like(y_test))

0.06516339261738034

In [333]:
metrics.hamming_loss(y_train, np.zeros_like(y_train))

0.06505498446091322

In [329]:
metrics.jaccard_score(y_train, train_predict, average = "micro")

0.5463362234328244

In [330]:
metrics.jaccard_score(y_train, train_predict, average = "macro")

0.35325215389262987

In [328]:
metrics.multilabel_confusion_matrix(y_train.values, train_predict)

array([[[5371,  339],
        [1101, 1555]],

       [[7549,   34],
        [ 578,  205]],

       [[6992,  114],
        [ 819,  441]],

       [[8286,    4],
        [  58,   18]],

       [[8339,    1],
        [  14,   12]],

       [[8294,    1],
        [  47,   24]],

       [[7292,   36],
        [ 728,  310]],

       [[6533,  203],
        [ 978,  652]],

       [[8340,    1],
        [  20,    5]],

       [[8357,    0],
        [   6,    3]],

       [[8244,    3],
        [  77,   42]],

       [[8195,    3],
        [ 104,   64]],

       [[7912,    8],
        [ 325,  121]],

       [[ 159,  367],
        [  14, 7826]],

       [[8362,    0],
        [   2,    2]],

       [[8302,    1],
        [  38,   25]],

       [[8261,    0],
        [  78,   27]],

       [[8324,    1],
        [  27,   14]],

       [[8330,    1],
        [  23,   12]],

       [[8363,    0],
        [   2,    1]],

       [[8356,    1],
        [   3,    6]],

       [[8273,    0],
        [  67,   26]],

       [[8357,    0],
        [   4,    5]],

       [[7370,   30],
        [ 658,  308]],

       [[8324,    2],
        [  27,   13]],

       [[8197,    0],
        [ 133,   36]],

       [[8048,    4],
        [ 206,  108]],

       [[7462,   34],
        [ 611,  259]],

       [[8179,    5],
        [ 122,   60]],

       [[8333,    0],
        [  21,   12]],

       [[8343,    0],
        [  12,   11]],

       [[8234,    0],
        [ 100,   32]],

       [[8339,    0],
        [  17,   10]],

       [[8308,    1],
        [  41,   16]],

       [[8100,    5],
        [ 184,   77]],

       [[6199,  167],
        [1062,  938]],

       [[3696,  956],
        [ 993, 2721]],

       [[7473,   26],
        [ 577,  290]],

       [[8283,    2],
        [  56,   25]],

       [[8364,    0],
        [   2,    0]],

       [[8201,    1],
        [ 132,   32]],

       [[7684,   16],
        [ 507,  159]],

       [[8362,    0],
        [   3,    1]],

       [[8278,    0],
        [  70,   18]],

       [[7941,   15],
        [ 288,  122]],

       [[8171,    2],
        [ 138,   55]],

       [[8264,    1],
        [  54,   47]],

       [[8300,    0],
        [  61,    5]],

       [[8107,    3],
        [ 175,   81]],

       [[8037,    6],
        [ 205,  118]],

       [[8359,    0],
        [   2,    5]],

       [[8337,    0],
        [  16,   13]],

       [[8336,    0],
        [  12,   18]],

       [[8271,    1],
        [  61,   33]],

       [[8347,    0],
        [  15,    4]],

       [[8018,    4],
        [ 264,   80]],

       [[8239,    1],
        [  88,   38]],

       [[1970, 1367],
        [ 641, 4388]],

       [[ 693,  995],
        [  92, 6586]],

       [[8143,    4],
        [ 141,   78]],

       [[8286,    0],
        [  47,   33]],

       [[8329,    0],
        [  27,   10]],

       [[8341,    1],
        [  17,    7]],

       [[8084,    6],
        [ 214,   62]],

       [[8232,    1],
        [  87,   46]],

       [[8325,    1],
        [  29,   11]],

       [[8024,    4],
        [ 204,  134]],

       [[8141,    4],
        [ 142,   79]],

       [[8204,    0],
        [ 110,   52]],

       [[8323,    3],
        [  24,   16]],

       [[8032,    3],
        [ 249,   82]],

       [[8350,    0],
        [  12,    4]],

       [[8361,    0],
        [   4,    1]],

       [[8344,    0],
        [  13,    9]],

       [[8360,    0],
        [   4,    2]],

       [[8337,    0],
        [  14,   15]],

       [[8354,    0],
        [   8,    4]],

       [[8355,    0],
        [   6,    5]],

       [[7130,   51],
        [ 819,  366]],

       [[8363,    0],
        [   1,    2]],

       [[8357,    0],
        [   7,    2]],

       [[8357,    0],
        [   3,    6]],

       [[8361,    0],
        [   0,    5]],

       [[8336,    0],
        [  13,   17]],

       [[8300,    2],
        [  41,   23]],

       [[8312,    0],
        [  29,   25]],

       [[7371,   46],
        [ 522,  427]],

       [[5439,  395],
        [1258, 1274]],

       [[8134,    5],
        [ 163,   64]],

       [[8187,    4],
        [ 118,   57]],

       [[8362,    0],
        [   4,    0]],

       [[5641,  434],
        [ 979, 1312]],

       [[7754,   21],
        [ 433,  158]],

       [[5783,  320],
        [ 984, 1279]],

       [[8257,    2],
        [  77,   30]],

       [[8230,    1],
        [ 103,   32]],

       [[7183,   51],
        [ 865,  267]],

       [[8242,    0],
        [ 111,   13]],

       [[6511,  167],
        [1056,  632]],

       [[7895,   14],
        [ 331,  126]],

       [[7444,   55],
        [ 544,  323]],

       [[7855,   11],
        [ 343,  157]],

       [[7908,   17],
        [ 222,  219]],

       [[8326,    0],
        [  25,   15]],

       [[8351,    0],
        [  10,    5]],

       [[8364,    0],
        [   2,    0]],

       [[8363,    1],
        [   1,    1]],

       [[8364,    0],
        [   2,    0]]])